### ISSUE TITLE
Compiling for Linux

### ISSUE THREAD

**Issue by votex09** [FLSoz/terratech-steam-mod-loader#2]
Can you provide documentation building this from source, or provide a Linux Binary?

**Comment by kiven7e** [comment]
i attempt's to build this in general (ive never built a ts app before) im running manjaro linux and had to install a few dependency after running ```npm install -g typescript  ``` i had to install a couple npm deps ```npm i react-router-dom@5.3 react-router @testing-library/react ps-list electron-updater electron-log electron react``` but i had a few errors like in the file terratech-steam-mod-loader-1.7.8/node_modules/@types/react-router-dom/index.d.ts ```Module "react-router" has no exported member, PromptProps, Prompt,  RedirectProps, RouteComponentProps, StaticRouterProps, StaticRouter, SwitchProps, Switch, match, withRouter, RouterChildContext, useHistory, useRouteMatch```  i could not get it to build sadly

**Comment by FLSoz** [comment]
To install on linux (I did it on ubuntu 20.04 LTS):
- Install node & npm. I'm using node version 16.10.0
- Checkout repository
- cd release/app
- npm install --save --ignore-scripts git+https://github.com/FLSoz/greenworks.git
- Get steamworks SDK, and install in proper deps directory. Follow steps here to do it: https://github.com/greenheartgames/greenworks/blob/master/docs/get-steamworks-sdk.md
- npm install
- cd ../../  (should now be in repository root directory)
- npm install
- npm run build

A built executable should be put into the `release/build` directory

**Comment by RunningDroid** [comment]
A shell script for people following along: [linux_build.sh](https://gist.github.com/RunningDroid/63bd47788de686c049e2939be367cbba)

@FLSoz I had to `npm install`  ts-node in release/app and @types/node at the root of the repo to get the build to not error out, but for some reason it doesn't create the release/build directory. The build isn't throwing any errors and if I do `npm start` it launches fine, so I don't know what's gone wrong.

**Comment by votex09** [comment]
I'll have to take a look - I'm on arch, and have been away from Terratech as a whole for a while now.

But, looks like @FLSoz included an AppImage in the last build
![image](https://github.com/FLSoz/terratech-steam-mod-loader/assets/10671494/c12dd2da-ba8e-4527-97ca-03e9cba81ace)

Thanks for that!

**Comment by votex09** [comment]
Seems to have failed on Arch during electron-rebuild
[https://pastebin.com/cA0f1MXG](url)

After `npm install ts-node` in ./release/app:
[https://pastebin.com/aCV8xb59](url)

after `npm install @types/node` in ./:
`mv: inter-device move failed: '/tmp/tmp.TdvSmpcoIJ/sdk' to 'node_modules/greenworks/deps/steamworks_sdk/sdk'; unable to remove target: Directory not empty`

Strange?
