### ISSUE TITLE
TTSMM v1.7.8 Game detected as running.

### ISSUE THREAD

**Issue by SmartGuy202** [FLSoz/terratech-steam-mod-loader#3]
Looking through the posted changelog, seems to be similar to a bug reported as fixed in v1.5.5

When starting TTSMM, Steam then detects TerraTech as running, thus the "Launch Game" option in TTSMM is disabled.

EDIT: Reconsidering posting this. With this version released in Sept, I have to imagine others would have run into this before me.

**Comment by SmartGuy202** [comment]
Downgrade to v1.7.7 resolves the issue.

**Comment by FLSoz** [comment]
Steam recognizing it as running is intended behaviour
